version: '3.8'

services:
  medapp-db:
    image: mysql:8.0
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_DATABASE: medapp
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: